Repository prgrms-be-devcourse/NBE2-3-2-team8, pull requests merged in 2025-01, with the labels that each got.

#86 [feat] 관리자 로그인 기능 추가
  src/main/java/org/programmers/signalbuddy/domain/admin/controller/AdminController.java
  src/main/java/org/programmers/signalbuddy/domain/admin/controller/AdminWebController.java
  src/main/java/org/programmers/signalbuddy/domain/admin/dto/AdminJoinRequest.java
  src/main/java/org/programmers/signalbuddy/domain/admin/service/AdminService.java
  src/main/java/org/programmers/signalbuddy/global/config/SecurityConfig.java
  src/main/java/org/programmers/signalbuddy/global/security/CustomUserDetails.java
  src/main/java/org/programmers/signalbuddy/global/security/filter/UserAuthenticationFilter.java
  src/main/java/org/programmers/signalbuddy/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/resources/templates/admin/loginform.html
Labels: Feature

#89 feat: 관리자 회원관리 프론트 작업
  q
  src/main/java/org/programmers/signalbuddy/domain/member/controller/MemberController.java
  src/main/resources/static/css/admin/list.css
  src/main/resources/templates/admin/list.html
  src/main/resources/templates/admin/withdrawal.html
Labels: Feature

#95 [fix] 소셜로그인 인가 버그 해결
  src/main/java/org/programmers/signalbuddy/global/security/oauth/CustomOAuth2User.java
Labels: Bug

#97 [feat] 관리자 메인페이지 프론트 작업
  src/main/java/org/programmers/signalbuddy/domain/admin/controller/AdminWebController.java
  src/main/resources/static/css/admin/main.css
  src/main/resources/templates/admin/list.html
  src/main/resources/templates/admin/main.html
Labels: Feature

#113 [fix] 계정 관련 버그 수정
  src/main/java/org/programmers/signalbuddy/domain/admin/controller/AdminWebController.java
  src/main/java/org/programmers/signalbuddy/domain/member/controller/MemberWebController.java
  src/main/java/org/programmers/signalbuddy/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/org/programmers/signalbuddy/global/security/oauth/CustomOAuth2UserService.java
  src/main/resources/templates/admin/loginform.html
  src/main/resources/templates/member/loginform.html
  src/main/resources/templates/member/signup.html
Labels: Bug

#115 [refactor] 회원 정보 수정 페이지 리팩터링
  src/main/java/org/programmers/signalbuddy/domain/member/controller/MemberController.java
  src/main/java/org/programmers/signalbuddy/domain/member/controller/MemberWebController.java
  src/main/java/org/programmers/signalbuddy/domain/member/service/MemberService.java
  src/main/resources/static/css/feedback/list.css
  src/main/resources/static/css/member/info.css
  src/main/resources/static/js/member/member.js
  src/main/resources/templates/feedback/list.html
  src/main/resources/templates/member/edit.html
  src/main/resources/templates/member/info.html
Labels: Refactor

#118 [feat] 117 경로탐색 기능
  src/main/resources/static/js/crossroad/tMap.js
  src/main/resources/templates/main.html
Labels: Feature

#120 [feat,style] : UI 변경
  src/main/resources/static/css/crossroad/signal.css
  src/main/resources/static/js/crossroad/tMap.js
  src/main/resources/templates/main.html
Labels: Feature, Style

#135 [feat] 즐겨찾기 등록 및 수정 페이지 Map, Marker 추가
  src/main/resources/static/js/member/bookmark/create.js
  src/main/resources/static/js/member/bookmark/update.js
  src/main/resources/templates/member/bookmark/add.html
  src/main/resources/templates/member/bookmark/edit.html
Labels: Feature

#139 [fix] submodule만 git clone 되는 문제 해결
  jenkins/main.jenkinsfile
Labels: Bug, CD
